name: trading
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py311hee9e2a2_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alembic=1.17.2=pyhd8ed1ab_0
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h41ebd0a_3
  - aws-c-cal=0.9.2=hd08b81e_1
  - aws-c-common=0.12.4=h6caf38d_0
  - aws-c-compression=0.3.1=habbe1e8_6
  - aws-c-event-stream=0.5.6=hf65d68d_3
  - aws-c-http=0.10.4=h70a9c10_3
  - aws-c-io=0.22.0=h89d1e94_1
  - aws-c-mqtt=0.13.3=he7b126b_6
  - aws-c-s3=0.8.6=h7a3c519_5
  - aws-c-sdkutils=0.2.4=habbe1e8_1
  - aws-checksums=0.2.7=habbe1e8_2
  - aws-crt-cpp=0.34.4=h01415d0_0
  - aws-sdk-cpp=1.11.606=h2169b1b_4
  - azure-core-cpp=1.16.0=h88fedcc_1
  - azure-identity-cpp=1.12.0=hd83eed2_0
  - azure-storage-blobs-cpp=12.14.0=he094cc7_1
  - azure-storage-common-cpp=12.10.0=h12fd690_2
  - azure-storage-files-datalake-cpp=12.12.0=h30213e0_3
  - bcrypt=5.0.0=py311h71babbd_1
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotli-python=1.1.0=py311hf719da1_4
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachetools=6.2.2=pyhd8ed1ab_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh707e725_0
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - contourpy=1.3.3=py311h5a5e7c7_3
  - cryptography=46.0.3=py311h054b3d0_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - databricks-sdk=0.73.0=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - dnspython=2.8.0=pyhcf101f3_0
  - docker-py=7.1.0=pyhd8ed1ab_1
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.3=h982b769_0
  - fastapi=0.121.3=hf029e93_0
  - fastapi-cli=0.0.16=pyhcf101f3_1
  - fastapi-core=0.121.3=pyhcf101f3_0
  - flask=3.1.2=pyhd8ed1ab_0
  - flask-cors=6.0.1=pyhe01879c_0
  - fonttools=4.60.1=py311ha9b3269_0
  - freetype=2.14.1=hce30654_0
  - gflags=2.2.2=hf9b8971_1005
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glog=0.7.1=heb240a5_0
  - google-auth=2.43.0=pyhd8ed1ab_0
  - graphene=3.4.3=pyhd8ed1ab_1
  - graphql-core=3.2.7=pyhcf101f3_0
  - graphql-relay=3.2.0=pyhd8ed1ab_1
  - greenlet=3.2.4=py311hf719da1_1
  - gunicorn=23.0.0=py311h267d04e_3
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py311h9408147_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=hc8870d7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - invoke=2.2.1=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py311h26d6576_2
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=21.0.0=hd43feaf_8_cpu
  - libarrow-acero=21.0.0=hc317990_8_cpu
  - libarrow-compute=21.0.0=h75845d1_8_cpu
  - libarrow-dataset=21.0.0=hc317990_8_cpu
  - libarrow-substrait=21.0.0=h144af7f_8_cpu
  - libblas=3.11.0=1_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.11.0=1_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.3=haf25636_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=1_hd9741b5_openblas
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=21.0.0=h45c8936_8_cpu
  - libpng=1.6.51=hfab5511_0
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.11.05=h91c62da_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.0=h9a5124b_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.0=hfce79cd_1
  - libutf8proc=2.11.1=hd2415e0_0
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.6=h4a912ad_0
  - lz4-c=1.10.0=h286801f_1
  - mako=1.3.10=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib-base=3.10.8=py311h29553df_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mlflow-ui=3.5.1=py311h267d04e_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - nlohmann_json=3.12.0=h248ca61_1
  - numpy=2.3.5=py311h8685306_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.6.0=h5503f6c_0
  - opentelemetry-api=1.38.0=pyhd8ed1ab_0
  - opentelemetry-proto=1.38.0=pyhd8ed1ab_0
  - opentelemetry-sdk=1.38.0=pyhd8ed1ab_0
  - opentelemetry-semantic-conventions=0.59b0=pyh3cfb1c2_0
  - orc=2.2.1=h4fd0076_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hdb8e4fa_1
  - paramiko=4.0.0=pyhd8ed1ab_0
  - pip=25.3=pyhc872135_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.2=pyhd8ed1ab_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pyarrow-core=21.0.0=py311hf3e52b4_1_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pydantic=2.12.4=pyh3cfb1c2_0
  - pydantic-core=2.41.5=py311h71babbd_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynacl=1.6.0=py311h9408147_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.11=h89a136b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - qhull=2020.2=h420ef59_5
  - querystring_parser=1.2.4=pyhd8ed1ab_2
  - re2=2025.11.05=h64b956e_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.16.0=pyhcf101f3_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py311h0f965f6_0
  - scipy=1.16.3=py311h2734c94_1
  - setuptools=80.9.0=py311hca03da5_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sqlalchemy=2.0.44=py311h9408147_0
  - sqlite=3.51.0=hab6afd1_0
  - sqlparse=0.5.3=pyhd8ed1ab_0
  - starlette=0.50.0=pyhfdc7a7d_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hcd8a7d5_0
  - tomli=2.3.0=pyhcf101f3_0
  - typer=0.20.0=pyhefaf540_1
  - typer-slim=0.20.0=pyhcf101f3_1
  - typer-slim-standard=0.20.0=h4daf872_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=17.0.0=py311h9408147_1
  - uvicorn=0.38.0=pyh31011fe_0
  - uvicorn-standard=0.38.0=h31011fe_0
  - uvloop=0.22.1=py311h9408147_1
  - watchfiles=1.1.1=py311h0f0954d_0
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py311hca03da5_0
  - wrapt=1.17.3=py311h3696347_1
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=py311ha9b3269_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstandard=0.25.0=py311h5bb9006_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - aiodns==3.5.0
      - alpaca-trade-api==3.2.0
      - altair==5.5.0
      - backtrader==1.9.78.123
      - build==1.3.0
      - ccxt==4.5.20
      - cffi==2.0.0
      - coincurve==21.0.0
      - colorlog==6.10.1
      - deprecation==2.1.0
      - frozenlist==1.8.0
      - huey==2.5.4
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lightgbm==4.6.0
      - matplotlib==3.10.7
      - mlflow==3.6.0
      - mlflow-skinny==3.6.0
      - mlflow-tracing==3.6.0
      - msgpack==1.0.3
      - multidict==6.7.0
      - narwhals==2.12.0
      - optuna==4.6.0
      - pillow==12.0.0
      - plotly==6.5.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - psycopg2-binary==2.9.11
      - pyarrow==21.0.0
      - pycares==4.11.0
      - pycparser==2.23
      - pydeck==0.9.1
      - pyproject-hooks==1.2.0
      - pyyaml==6.0.1
      - redis==7.1.0
      - referencing==0.37.0
      - rpds-py==0.29.0
      - streamlit==1.51.0
      - ta-lib==0.6.8
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5.2
      - tqdm==4.67.1
      - urllib3==1.26.20
      - websockets==10.4
      - xgboost==3.1.2
prefix: /opt/miniconda3/envs/trading
