name: trading
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - yfinance
  - requests
  - pip
  - pip:
      - plotly
      - dash

