name: trading
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiodns==3.5.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alembic==1.17.2
      - alpaca-trade-api==3.2.0
      - altair==5.5.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - backtrader==1.9.78.123
      - blinker==1.9.0
      - build==1.3.0
      - cachetools==6.2.2
      - ccxt==4.5.20
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - coincurve==21.0.0
      - colorlog==6.10.1
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - databricks-sdk==0.73.0
      - deprecation==2.1.0
      - docker==7.1.0
      - fastapi==0.121.3
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.43.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - httptools==0.7.1
      - huey==2.5.4
      - idna==3.11
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lightgbm==4.6.0
      - mako==1.3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mlflow==3.6.0
      - mlflow-skinny==3.6.0
      - mlflow-tracing==3.6.0
      - msgpack==1.0.3
      - multidict==6.7.0
      - narwhals==2.12.0
      - numpy==2.3.5
      - opentelemetry-api==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - optuna==4.6.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - plotly==6.5.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - psycopg2-binary==2.9.11
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycares==4.11.0
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - pyparsing==3.2.5
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.1
      - redis==7.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.29.0
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - starlette==0.50.0
      - streamlit==1.51.0
      - ta-lib==0.6.8
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - tornado==6.5.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==1.26.20
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==10.4
      - werkzeug==3.1.3
      - xgboost==3.1.2
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /opt/miniconda3/envs/trading
